services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linker
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=linkeradmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always
volumes:
  minio_data:
    driver: local
