// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :exec
INSERT INTO links(
  user_id,
	url,
	title,
	description,
	created_at
) values(
  $1,$2,$3,$4,NOW()
)
`

type CreateLinkParams struct {
	UserID      int32
	Url         string
	Title       string
	Description string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.Exec(ctx, createLink,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Description,
	)
	return err
}

const findAllLinksFromAUser = `-- name: FindAllLinksFromAUser :many
SELECT id, user_id, url, title, description, created_at FROM links where user_id = $1
`

func (q *Queries) FindAllLinksFromAUser(ctx context.Context, userID int32) ([]Link, error) {
	rows, err := q.db.Query(ctx, findAllLinksFromAUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
