// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int32
	UserID      int32
	Url         string
	Title       string
	Description string
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID             int32
	Email          string
	Password       string
	CreatedAt      pgtype.Timestamp
	ProfilePicture string
	Bio            string
	BannerPicture  string
	Name           pgtype.Text
}
