// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, email, password, name) values(default, $1, $2,$3) RETURNING id
`

type CreateUserParams struct {
	Email    string
	Password string
	Name     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, profile_picture, bio, banner_picture, name FROM users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ProfilePicture,
		&i.Bio,
		&i.BannerPicture,
		&i.Name,
	)
	return i, err
}

const updateBannerPhoto = `-- name: UpdateBannerPhoto :exec
UPDATE users set banner_picture = $1 where email = $2
`

type UpdateBannerPhotoParams struct {
	BannerPicture string
	Email         string
}

func (q *Queries) UpdateBannerPhoto(ctx context.Context, arg UpdateBannerPhotoParams) error {
	_, err := q.db.Exec(ctx, updateBannerPhoto, arg.BannerPicture, arg.Email)
	return err
}

const updateBio = `-- name: UpdateBio :exec
UPDATE users set bio = $1 where email = $2
`

type UpdateBioParams struct {
	Bio   string
	Email string
}

func (q *Queries) UpdateBio(ctx context.Context, arg UpdateBioParams) error {
	_, err := q.db.Exec(ctx, updateBio, arg.Bio, arg.Email)
	return err
}

const updateProfilePhoto = `-- name: UpdateProfilePhoto :exec
UPDATE users set profile_picture = $1 where email = $2
`

type UpdateProfilePhotoParams struct {
	ProfilePicture string
	Email          string
}

func (q *Queries) UpdateProfilePhoto(ctx context.Context, arg UpdateProfilePhotoParams) error {
	_, err := q.db.Exec(ctx, updateProfilePhoto, arg.ProfilePicture, arg.Email)
	return err
}
